var annotated_dup =
[
    [ "ipaddress", "namespaceipaddress.html", [
      [ "base_v4", "classipaddress_1_1base__v4.html", "classipaddress_1_1base__v4" ],
      [ "base_v6", "classipaddress_1_1base__v6.html", "classipaddress_1_1base__v6" ],
      [ "byte_array", "structipaddress_1_1byte__array.html", "structipaddress_1_1byte__array" ],
      [ "error", "classipaddress_1_1error.html", "classipaddress_1_1error" ],
      [ "exclude_network_sequence", "classipaddress_1_1exclude__network__sequence.html", "classipaddress_1_1exclude__network__sequence" ],
      [ "fixed_string", "structipaddress_1_1fixed__string.html", "structipaddress_1_1fixed__string" ],
      [ "fixed_vector", "classipaddress_1_1fixed__vector.html", "classipaddress_1_1fixed__vector" ],
      [ "fixed_vector_iterator", "classipaddress_1_1fixed__vector__iterator.html", "classipaddress_1_1fixed__vector__iterator" ],
      [ "hosts_any_sequence", "classipaddress_1_1hosts__any__sequence.html", "classipaddress_1_1hosts__any__sequence" ],
      [ "hosts_sequence< ip_address_base< Base > >", "classipaddress_1_1hosts__sequence_3_01ip__address__base_3_01Base_01_4_01_4.html", "classipaddress_1_1hosts__sequence_3_01ip__address__base_3_01Base_01_4_01_4" ],
      [ "ip_address", "classipaddress_1_1ip__address.html", "classipaddress_1_1ip__address" ],
      [ "ip_address_base", "classipaddress_1_1ip__address__base.html", "classipaddress_1_1ip__address__base" ],
      [ "ip_address_iterator< ip_address_base< Base > >", "classipaddress_1_1ip__address__iterator_3_01ip__address__base_3_01Base_01_4_01_4.html", "classipaddress_1_1ip__address__iterator_3_01ip__address__base_3_01Base_01_4_01_4" ],
      [ "ip_any_iterator", "classipaddress_1_1ip__any__iterator.html", "classipaddress_1_1ip__any__iterator" ],
      [ "ip_any_summarize_iterator", "classipaddress_1_1ip__any__summarize__iterator.html", "classipaddress_1_1ip__any__summarize__iterator" ],
      [ "ip_exclude_network_iterator", "classipaddress_1_1ip__exclude__network__iterator.html", "classipaddress_1_1ip__exclude__network__iterator" ],
      [ "ip_network", "classipaddress_1_1ip__network.html", "classipaddress_1_1ip__network" ],
      [ "ip_network_base", "classipaddress_1_1ip__network__base.html", "classipaddress_1_1ip__network__base" ],
      [ "ip_network_iterator", "classipaddress_1_1ip__network__iterator.html", "classipaddress_1_1ip__network__iterator" ],
      [ "ip_reverse_iterator", "classipaddress_1_1ip__reverse__iterator.html", "classipaddress_1_1ip__reverse__iterator" ],
      [ "ip_summarize_iterator", "classipaddress_1_1ip__summarize__iterator.html", "classipaddress_1_1ip__summarize__iterator" ],
      [ "ipv4_address_base", "classipaddress_1_1ipv4__address__base.html", "classipaddress_1_1ipv4__address__base" ],
      [ "ipv4_network_base", "classipaddress_1_1ipv4__network__base.html", "classipaddress_1_1ipv4__network__base" ],
      [ "ipv6_address_base", "classipaddress_1_1ipv6__address__base.html", "classipaddress_1_1ipv6__address__base" ],
      [ "ipv6_network_base", "classipaddress_1_1ipv6__network__base.html", "classipaddress_1_1ipv6__network__base" ],
      [ "logic_error", "classipaddress_1_1logic__error.html", "classipaddress_1_1logic__error" ],
      [ "optional", "classipaddress_1_1optional.html", "classipaddress_1_1optional" ],
      [ "parse_error", "classipaddress_1_1parse__error.html", "classipaddress_1_1parse__error" ],
      [ "scope", "classipaddress_1_1scope.html", "classipaddress_1_1scope" ],
      [ "subnets_any_sequence", "classipaddress_1_1subnets__any__sequence.html", "classipaddress_1_1subnets__any__sequence" ],
      [ "subnets_sequence", "classipaddress_1_1subnets__sequence.html", "classipaddress_1_1subnets__sequence" ],
      [ "summarize_sequence", "classipaddress_1_1summarize__sequence.html", "classipaddress_1_1summarize__sequence" ],
      [ "uint128_t", "classipaddress_1_1uint128__t.html", "classipaddress_1_1uint128__t" ]
    ] ]
];