name: Doxygen GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get -y install doxygen

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }}
            -DCMAKE_CXX_COMPILER=clang++
            -DCMAKE_C_COMPILER=clang
            -DCMAKE_BUILD_TYPE=Release
            -DIPADDRESS_BUILD_TESTS=OFF
            -DIPADDRESS_BUILD_DOC=ON

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

#       - run: mkdir docs
#       - name: Install theme
#         run: ./tools/prepare_doxygen.sh
#       - name: Generate Doxygen Documentation
#         run: doxygen
