name: Publish to Launchpad PPA
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Debuild
        run: sudo apt install -y devscripts
     
      - name: Set build output dir
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          echo "version=0.0.3" >> "$GITHUB_OUTPUT"
          echo "build=1" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }}
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_BUILD_TYPE=Release
          -DIPADDRESS_BUILD_TESTS=OFF
          -DIPADDRESS_BUILD_DOC=OFF
          -DIPADDRESS_BUILD_PACKAGES=ON
          -DIPADDRESS_BUILD_DEB_PACKAGE=ON
          -DIPADDRESS_BUILD_RPM_PACKAGE=OFF

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release
        
      - name: Pack Deb
        run: cpack --config ${{ steps.strings.outputs.build-output-dir }}/CPackConfig.cmake

      - name: Add .orig.tar.gz
        run: |
          mkdir -p ${{ steps.strings.outputs.build-output-dir }}/ppa
          mkdir -p ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}
          mkdir -p ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian
          mkdir -p ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/source
          cp _CPack_Packages/Linux/DEB/ipaddress-${{ steps.strings.outputs.version }}/data.tar.gz ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress_${{ steps.strings.outputs.version }}.orig.tar.gz

      - name: Add debian/rules
        run: |
          printf "#!/usr/bin/make -f\n
          
          %%:
          	dh \$@\n
          " >  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/rules

      - name: Add changelog
        run: |
          printf "ipaddress (${{ steps.strings.outputs.version }}-${{ steps.strings.outputs.build }}) focal; urgency=low\n
          
            * Release ${{ steps.strings.outputs.version }}.\n
          
           -- Vladimir Shaleev <vladimirshaleev@gmail.com>  " >  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/changelog
          date +"%a, %d %b %Y %H:%M:%S %z" >>  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/changelog

      - name: Add debian/compat and debian/format
        run: |
          echo 10 >  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/compat
          echo "3.0 (quilt)" >  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/source/format

      - name: Add debian/control
        run: |
          printf "Source: ipaddress
          Section: devel
          Priority: optional
          Maintainer: Vladimir Shaleev <vladimirshaleev@gmail.com>
          Standards-Version: 4.5.0
          Build-Depends: debhelper (>= 10)\n
          
          Package: libipaddress-dev
          Depends: \${misc:Depends}
          Architecture: all
          Homepage: https://github.com/VladimirShaleev/ipaddress
          Description: A library for working and manipulating IPv4/IPv6 addresses and networks\n\n
          " >  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/control
      - name: Add copyright
        run: printf "stup" > ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/copyright

      - name: test
        run: |
          cat  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/rules
          cat  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/compat
          cat  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/source/format
          cat  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/changelog
          cat  ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}/debian/control
  
      - name: Debuild
        run: |
          cd ${{ steps.strings.outputs.build-output-dir }}/ppa/ipaddress-${{ steps.strings.outputs.version }}
          debuild -S -sa -us -uc
